[package]
name = "addgen"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3


[dependencies]
core_affinity = "0.8.1"
crossbeam = "0.8.3"
hex = "0.4.3"
num_cpus = "1.16.0"
packed_simd = "0.3.9"
rand = "0.8.5"
secp256k1 = "0.28.0"
sha3 = "0.10.8"
